CREATE TABLE LOAN_ACCOUNTS
(
 Accno char(4),
 Cust_name varchar(15),
 Loan_Amount Numeric(8,2),
 Installments Numeric,
 int_rate VARCHAR(20),
 start_date DATE ,
 Interest Numeric(8)
 );
 DESC LOAN_ACCOUNTS;
 DROP TABLE LOAN_ACCOUNTS;
 TRUNCATE TABLE LOAN_ACCOUNTS;
 ALTER TABLE LOAN_ACCOUNTS ADD COLUMN category varchar(21);
 DESC LOAN_ACCOUNTS;
INSERT INTO LOAN_ACCOUNTS(Accno,Cust_name,Loan_Amount,Installments,int_rate,start_date) VALUES
(1001,  'R.K Gupta',    300000.00,  36,   12.00, '2009-7-19'),
(1002	,'S.P Sharma',  500000.00,  48,   10.00, '2008-3-22'),
(1003	,'K.P Jain',    300000.00,  36,   'NULL','2007-8-3'),
(1004	,'M.P Yadav',	800000.00,	60,    10.00,'2008-6-12'),
(1005	,'S.P Sinha',	200000.00,	36,	   12.50,'2010-3-1'),
(1006	,'P. Sharma',	700000.00,	60	,  12.50, '2008-5-6'),
(1007	,'K.S Dhall',	500000.00,	48	,  'NULL','2008-5-3');
SELECT * FROM LOAN_ACCOUNTS;
UPDATE LOAN_ACCOUNTS SET int_rate=11.50 WHERE int_rate='NULL';
SELECT * FROM LOAN_ACCOUNTS;
UPDATE LOAN_ACCOUNTS SET int_rate=int_rate+(0.5/100) WHERE Loan_Amount >400000;
SELECT * FROM LOAN_ACCOUNTS;
UPDATE LOAN_ACCOUNTS SET Interest =(Loan_amount * int_rate* Installments)/(12*100) ;
DELETE FROM LOAN_ACCOUNTS where YEAR(start_date) <2008;
SELECT * FROM LOAN_ACCOUNTS;
DELETE FROM LOAN_ACCOUNTS where (Cust_name LIKE 'K%');

SELECT * FROM LOAN_ACCOUNTS;
SELECT * FROM LOAN_ACCOUNTS where Installments<40;
SELECT Accno,Loan_Amount FROM LOAN_ACCOUNTS WHERE start_date <'2009-4-1';
SELECT int_rate FROM LOAN_ACCOUNTS WHERE start_date >'2009-4-1';
SELECT Accno,Cust_name,Loan_Amount FROM LOAN_ACCOUNTS WHERE (Cust_name LIKE '%Sharma');
SELECT Loan_Amount FROM LOAN_ACCOUNTS WHERE (Cust_name Like '%a') ;
SELECT Accno,Cust_name,Loan_Amount FROM LOAN_ACCOUNTS WHERE (Cust_name LIKE '%a%');
SELECT Accno,Cust_name,Loan_Amount FROM LOAN_ACCOUNTS WHERE NOT (Cust_name LIKE '%P%');
DESC LOAN_ACCOUNTS;
SELECT *FROM LOAN_ACCOUNTS ORDER BY Loan_amount ASC;
SELECT *FROM LOAN_ACCOUNTS ORDER BY start_date DESC;
SELECT *FROM LOAN_ACCOUNTS ORDER BY Loan_amount,start_date DESC;
SELECT Accno,Cust_name,Loan_Amount FROM LOAN_ACCOUNTS WHERE (Cust_name LIKE '%k');
SELECT * FROM LOAN_ACCOUNTS WHERE int_rate IS NULL;
SELECT * FROM LOAN_ACCOUNTS WHERE int_rate IS NOT NULL;
SELECT DISTINCT Loan_Amount FROM LOAN_ACCOUNTS;
SELECT * FROM LOAN_ACCOUNTS where start_date>'2008-12-13' AND Installments=36;
SELECT Cust_name,Loan_Amount FROM LOAN_ACCOUNTS  where Loan_Amount<500000 or int_rate>12;
SELECT * FROM LOAN_ACCOUNTS WHERE year(start_date)>2009;
SELECT * FROM LOAN_ACCOUNTS WHERE Loan_Amount between 400000 AND 500000;
SELECT Cust_name,Loan_Amount FROM LOAN_ACCOUNTS WHERE Installments IN( 26, 36 , 48);
SELECT CUST_NAME,LOAN_AMOUNT,INT_RATE,
 CASE WHEN INT_RATE  IS NULL THEN '0' ELSE INT_RATE END FROM LOAN_ACCOUNTS;
 SELECT CUST_NAME,LOAN_AMOUNT,INT_RATE,
 CASE WHEN INT_RATE  IS NULL THEN 'No Interest' ELSE INT_RATE END FROM LOAN_ACCOUNTS;

